allowBuilds:
  '@prisma/engines': false
  esbuild: false
  ffmpeg-static: set this to true or false
  msgpackr-extract: false
  prisma: true
  workerd: false
minimumReleaseAgeExclude:
  - '@nestjs/observe@0.3.0'
